/**
 * Known-good output for each preset.
 *
 * A fixture is the matrix a preset's code actually produced when it was last
 * run against the real APL service. It gives us stable tests, thumbnails that
 * can be generated without a network, proof that the renderer works
 * independently of TryAPL, and a way to notice when a preset's output changes
 * without anyone meaning it to.
 *
 * Fixtures are refreshed deliberately with `npm run refresh:fixtures`, never
 * as a side effect of a build.
 */

import { type NumericMatrix } from '@/matrix/matrixTypes';
import { fromNested } from '@/matrix/matrixTypes';

export interface PresetFixture {
  readonly presetId: string;
  /** Of the code that produced it, so a drifting preset is detectable. */
  readonly codeHash: string;
  readonly rows: number;
  readonly columns: number;
  readonly values: readonly (readonly number[])[];
  readonly generatedAt: string;
}

/**
 * A small, stable digest of a preset's code.
 *
 * FNV-1a: not cryptographic, and it does not need to be. It only has to change
 * when the code changes, and be identical in Node and the browser so a fixture
 * generated by a script can be checked by a test.
 */
export function hashCode(code: string): string {
  let hash = 0x811c9dc5;
  for (let index = 0; index < code.length; index += 1) {
    hash ^= code.charCodeAt(index);
    // The usual FNV prime multiply, kept in 32 bits.
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash.toString(16).padStart(8, '0');
}

export function fixtureToMatrix(fixture: PresetFixture): NumericMatrix {
  return fromNested(fixture.values);
}

export type FixtureValidation = { readonly ok: true } | { readonly ok: false; readonly reason: string };

/** Checks a fixture is internally consistent and still matches its preset's code. */
export function validateFixture(fixture: PresetFixture, code: string): FixtureValidation {
  if (fixture.values.length !== fixture.rows) {
    return { ok: false, reason: `declares ${fixture.rows} rows but holds ${fixture.values.length}` };
  }

  for (const [index, row] of fixture.values.entries()) {
    if (row.length !== fixture.columns) {
      return {
        ok: false,
        reason: `row ${index} has ${row.length} values, expected ${fixture.columns}`,
      };
    }
  }

  if (fixture.codeHash !== hashCode(code)) {
    return {
      ok: false,
      reason: 'was generated from different code; run `npm run refresh:fixtures` to bring it up to date',
    };
  }

  return { ok: true };
}
